/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WisButton {
        "label": string;
    }
    interface WisCard {
        "cardTitle": string;
        "icon": string;
    }
    interface WisWeatherCard {
        "condition": string;
        "location": string;
        "temperature": string;
    }
}
declare global {
    interface HTMLWisButtonElement extends Components.WisButton, HTMLStencilElement {
    }
    var HTMLWisButtonElement: {
        prototype: HTMLWisButtonElement;
        new (): HTMLWisButtonElement;
    };
    interface HTMLWisCardElement extends Components.WisCard, HTMLStencilElement {
    }
    var HTMLWisCardElement: {
        prototype: HTMLWisCardElement;
        new (): HTMLWisCardElement;
    };
    interface HTMLWisWeatherCardElement extends Components.WisWeatherCard, HTMLStencilElement {
    }
    var HTMLWisWeatherCardElement: {
        prototype: HTMLWisWeatherCardElement;
        new (): HTMLWisWeatherCardElement;
    };
    interface HTMLElementTagNameMap {
        "wis-button": HTMLWisButtonElement;
        "wis-card": HTMLWisCardElement;
        "wis-weather-card": HTMLWisWeatherCardElement;
    }
}
declare namespace LocalJSX {
    interface WisButton {
        "label"?: string;
    }
    interface WisCard {
        "cardTitle"?: string;
        "icon"?: string;
    }
    interface WisWeatherCard {
        "condition"?: string;
        "location"?: string;
        "temperature"?: string;
    }
    interface IntrinsicElements {
        "wis-button": WisButton;
        "wis-card": WisCard;
        "wis-weather-card": WisWeatherCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wis-button": LocalJSX.WisButton & JSXBase.HTMLAttributes<HTMLWisButtonElement>;
            "wis-card": LocalJSX.WisCard & JSXBase.HTMLAttributes<HTMLWisCardElement>;
            "wis-weather-card": LocalJSX.WisWeatherCard & JSXBase.HTMLAttributes<HTMLWisWeatherCardElement>;
        }
    }
}
